# Based on https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel
default:
  image: node:16.16.0

test:
  stage: test
  script:
    - npm install
    - npm run test:coverage
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov
