# Run the following command to validate this file:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

# Based on https://docs.codecov.com/docs
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Based on https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
